/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBook: typeof import('./components/AddBook.vue')['default']
    AddDesc: typeof import('./components/AddDesc.vue')['default']
    Adminpw: typeof import('./components/Adminpw.vue')['default']
    Authcar: typeof import('./components/layouts/authcar.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    Cropper: typeof import('./components/Cropper.vue')['default']
    CropperJs: typeof import('./components/layouts/CropperJs.vue')['default']
    Editpas: typeof import('./components/Editpas.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCar: typeof import('element-plus/es')['ElCar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElFrom: typeof import('element-plus/es')['ElFrom']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImageUp: typeof import('./components/ImageUp.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Opauthor: typeof import('./components/opauthor.vue')['default']
    RoleCard: typeof import('./components/layouts/RoleCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sysviem: typeof import('./components/Sysviem.vue')['default']
  }
}
